name: commodity_cta
market: commodity
asset_class: commodity_futures
description: "Commodity futures CTA — multi-timeframe trend following, carry/roll yield, and momentum+value strategies on CME/ICE futures via Yahoo Finance"

universe:
  # Commodities (8)
  - CL=F    # WTI Crude Oil
  - NG=F    # Natural Gas
  - GC=F    # Gold
  - SI=F    # Silver
  - HG=F    # Copper
  - ZW=F    # Wheat
  - ZC=F    # Corn
  - ZS=F    # Soybeans
  # FX (4)
  - EURUSD=X
  - GBPUSD=X
  - AUDUSD=X
  - JPY=X
  # Bonds (2)
  - TLT     # 20yr Treasury ETF
  - IEF     # 10yr Treasury ETF

data_provider: yahoo_futures_v1
default_config: configs/rp_mom_dd_champion.json
cost_model: commodity_futures

features:
  - volume
  - open
  - high
  - low
  - atr_14
  - rv_20d
  - mom_20d
  - mom_60d
  - mom_120d
  - rsi_14
  - zscore_60d
  - ewma_signal
  - vol_mom_z
  - sector_momentum

strategies:
  - rp_mom_dd       # Champion (Phase 142)
  - cta_trend
  - cta_carry
  - cta_mom_value
  - cta_ensemble
  - cta_tsmom
  - cta_donchian
  - cta_ensemble_v2

brain_interval: 3600
enabled: true
