name: spx_pcs
market: equity
asset_class: put_credit_spread
description: >
  SPX 0DTE Put Credit Spread — custom Python+Rust backtest engine (algoxpert).
  Chiến lược bán put spread trên SPX index options, sử dụng VIX gate,
  delta selection và TP/SL exit logic.
universe:
  - SPX

data_provider: algoxpert_parquet
default_config: configs/spx_pcs_v1.json
cost_model: cboe_options

features:
  - vix_gate
  - delta_selection
  - wing_gap
  - tp_sl_exit
  - mean_reversion_bounce
  - rsi_oversold
  - bollinger_oversold

strategies:
  - spx_pcs_baseline
  - spx_pcs_mr_bounce
  - spx_pcs_combo_2of3
  - spx_pcs_rsi_oversold
  - spx_pcs_trend_retake

brain_interval: 3600
enabled: true

# External engine configuration — algoxpert runs independently
external_engine: true
external_engine_path: "${ALGOXPERT_DIR}"
external_engine_cmd: "python scripts/run_backtest.py"

# Status tracking
status: production_ready
phase: "3h"
validated_date: "2026-02-22"
champion_config: "configs/spx_pcs_v1.json"
champion_sharpe_5yr_avg: 5.428
champion_months_positive: "41/55"
inception_date: "2021-01-01"
notes: >
  Project 4 — SPX 0DTE PCS. Phase 3 COMPLETE. Champion: H_ref (d=0.20, sl=10, tp=0.5, time=375min).
  5yr avg Sharpe +5.428 (annualized monthly). True OOS 2025: +8.871, no degradation.
  Crash protection validated: Apr 2025 SPX -10% -> H_ref +8.04.
  All filters disproven (medium SL, VIX gate, VIX min).
  Staleness bias fix committed (04bb2c5), 0% impact confirmed.
  Engine: Python (polars) + Rust (maturin). Data: 41GB SPXW parquet 2020-2025.
  Deployment-ready pending live paper trading validation.
