"""
NEXUS Research Source Registry — 50+ curated, publicly accessible sources.

Each source has:
  name       : unique id
  label      : display name
  category   : "academic" | "blog" | "forum" | "crypto" | "ml" | "industry" | "news"
  url        : RSS feed URL or API endpoint
  kind       : "rss" | "reddit_rss" | "arxiv_api" | "coingecko_api" | "html"
  tags       : list of topic tags for relevance scoring
  weight     : default relevance weight (0.0–1.0)
"""
from __future__ import annotations
from typing import List, Dict, Any

SOURCES: List[Dict[str, Any]] = [
    # ── ACADEMIC ──────────────────────────────────────────────────────────────
    {
        "name": "arxiv_qfin_pm",
        "label": "arXiv q-fin Portfolio Management",
        "category": "academic",
        "url": "https://rss.arxiv.org/rss/q-fin.PM",
        "kind": "rss",
        "tags": ["portfolio", "optimization", "factor", "sharpe", "alpha"],
        "weight": 1.0,
    },
    {
        "name": "arxiv_qfin_tr",
        "label": "arXiv q-fin Trading",
        "category": "academic",
        "url": "https://rss.arxiv.org/rss/q-fin.TR",
        "kind": "rss",
        "tags": ["trading", "execution", "momentum", "carry", "mean_reversion"],
        "weight": 1.0,
    },
    {
        "name": "arxiv_cs_lg",
        "label": "arXiv cs.LG Machine Learning",
        "category": "academic",
        "url": "https://rss.arxiv.org/rss/cs.LG",
        "kind": "rss",
        "tags": ["machine_learning", "deep_learning", "reinforcement_learning", "lstm", "transformer"],
        "weight": 0.7,
    },
    {
        "name": "arxiv_qfin_cp",
        "label": "arXiv q-fin Computational Finance",
        "category": "academic",
        "url": "https://rss.arxiv.org/rss/q-fin.CP",
        "kind": "rss",
        "tags": ["computational", "simulation", "monte_carlo", "pricing", "backtest"],
        "weight": 0.9,
    },
    {
        "name": "arxiv_qfin_st",
        "label": "arXiv q-fin Statistical Finance",
        "category": "academic",
        "url": "https://rss.arxiv.org/rss/q-fin.ST",
        "kind": "rss",
        "tags": ["statistics", "time_series", "volatility", "regime", "correlation"],
        "weight": 0.9,
    },
    {
        "name": "arxiv_qfin_rm",
        "label": "arXiv q-fin Risk Management",
        "category": "academic",
        "url": "https://rss.arxiv.org/rss/q-fin.RM",
        "kind": "rss",
        "tags": ["risk", "var", "drawdown", "position_limit", "hedging"],
        "weight": 0.8,
    },
    {
        "name": "arxiv_qfin_gn",
        "label": "arXiv q-fin General",
        "category": "academic",
        "url": "https://rss.arxiv.org/rss/q-fin.GN",
        "kind": "rss",
        "tags": ["quantitative", "finance", "crypto", "market"],
        "weight": 0.7,
    },
    {
        "name": "arxiv_cs_ai",
        "label": "arXiv cs.AI Artificial Intelligence",
        "category": "academic",
        "url": "https://rss.arxiv.org/rss/cs.AI",
        "kind": "rss",
        "tags": ["agent", "reinforcement_learning", "planning", "autonomous"],
        "weight": 0.6,
    },
    {
        "name": "arxiv_econ_gn",
        "label": "arXiv econ General Economics",
        "category": "academic",
        "url": "https://rss.arxiv.org/rss/econ.GN",
        "kind": "rss",
        "tags": ["economics", "macro", "market_structure", "liquidity"],
        "weight": 0.6,
    },
    {
        "name": "nber_finance",
        "label": "NBER Working Papers (Finance)",
        "category": "academic",
        "url": "https://feeds.feedburner.com/NberNew",
        "kind": "rss",
        "tags": ["academic", "finance", "macro", "asset_pricing"],
        "weight": 0.8,
    },
    {
        "name": "bis_working_papers",
        "label": "BIS Working Papers",
        "category": "academic",
        "url": "https://www.bis.org/dcms/feeds/rss_fsb.xml",
        "kind": "rss",
        "tags": ["regulatory", "systemic_risk", "liquidity", "macro"],
        "weight": 0.5,
    },
    # ── ML / AI FORUMS ────────────────────────────────────────────────────────
    {
        "name": "papers_with_code_methods",
        "label": "Papers With Code (Methods)",
        "category": "ml",
        "url": "https://paperswithcode.com/methods/rss",
        "kind": "rss",
        "tags": ["machine_learning", "deep_learning", "sota", "benchmark"],
        "weight": 0.8,
    },
    {
        "name": "reddit_machinelearning",
        "label": "Reddit r/MachineLearning",
        "category": "ml",
        "url": "https://www.reddit.com/r/MachineLearning/top/.rss?t=week",
        "kind": "rss",
        "tags": ["machine_learning", "research", "neural_network", "llm"],
        "weight": 0.6,
    },
    {
        "name": "reddit_learnml",
        "label": "Reddit r/learnmachinelearning",
        "category": "ml",
        "url": "https://www.reddit.com/r/learnmachinelearning/top/.rss?t=week",
        "kind": "rss",
        "tags": ["machine_learning", "education", "tutorial"],
        "weight": 0.4,
    },
    {
        "name": "towards_data_science",
        "label": "Towards Data Science",
        "category": "ml",
        "url": "https://towardsdatascience.com/feed",
        "kind": "rss",
        "tags": ["data_science", "machine_learning", "python", "finance"],
        "weight": 0.5,
    },
    # ── TRADING FORUMS ────────────────────────────────────────────────────────
    {
        "name": "reddit_algotrading",
        "label": "Reddit r/algotrading",
        "category": "forum",
        "url": "https://www.reddit.com/r/algotrading/top/.rss?t=week",
        "kind": "rss",
        "tags": ["algo_trading", "backtest", "strategy", "quant", "momentum", "mean_reversion"],
        "weight": 1.0,
    },
    {
        "name": "reddit_quantfinance",
        "label": "Reddit r/quantfinance",
        "category": "forum",
        "url": "https://www.reddit.com/r/quantfinance/top/.rss?t=week",
        "kind": "rss",
        "tags": ["quant", "finance", "derivatives", "risk", "factor"],
        "weight": 0.9,
    },
    {
        "name": "reddit_securityanalysis",
        "label": "Reddit r/SecurityAnalysis",
        "category": "forum",
        "url": "https://www.reddit.com/r/SecurityAnalysis/top/.rss?t=week",
        "kind": "rss",
        "tags": ["fundamental", "analysis", "valuation", "research"],
        "weight": 0.4,
    },
    {
        "name": "stackexchange_quant",
        "label": "Stack Exchange Quantitative Finance",
        "category": "forum",
        "url": "https://quant.stackexchange.com/feeds",
        "kind": "rss",
        "tags": ["quant", "options", "derivatives", "risk", "pricing", "backtest"],
        "weight": 0.9,
    },
    {
        "name": "reddit_cryptocurrency",
        "label": "Reddit r/CryptoCurrency",
        "category": "forum",
        "url": "https://www.reddit.com/r/CryptoCurrency/top/.rss?t=week",
        "kind": "rss",
        "tags": ["crypto", "bitcoin", "ethereum", "defi", "funding_rate"],
        "weight": 0.7,
    },
    {
        "name": "reddit_defi",
        "label": "Reddit r/DeFi",
        "category": "forum",
        "url": "https://www.reddit.com/r/defi/top/.rss?t=week",
        "kind": "rss",
        "tags": ["defi", "yield", "liquidity", "protocol", "basis_trade"],
        "weight": 0.6,
    },
    {
        "name": "reddit_btc",
        "label": "Reddit r/Bitcoin",
        "category": "forum",
        "url": "https://www.reddit.com/r/Bitcoin/top/.rss?t=week",
        "kind": "rss",
        "tags": ["bitcoin", "macro", "adoption", "sentiment"],
        "weight": 0.5,
    },
    {
        "name": "reddit_ethfinance",
        "label": "Reddit r/ethfinance",
        "category": "forum",
        "url": "https://www.reddit.com/r/ethfinance/top/.rss?t=week",
        "kind": "rss",
        "tags": ["ethereum", "staking", "yield", "defi"],
        "weight": 0.5,
    },
    # ── QUANT FINANCE BLOGS ───────────────────────────────────────────────────
    {
        "name": "quantocracy",
        "label": "Quantocracy (Quant Blog Aggregator)",
        "category": "blog",
        "url": "https://quantocracy.com/feed/",
        "kind": "rss",
        "tags": ["quant", "strategy", "backtest", "factor", "momentum", "carry"],
        "weight": 1.0,
    },
    {
        "name": "alpha_architect",
        "label": "Alpha Architect Blog",
        "category": "blog",
        "url": "https://alphaarchitect.com/feed/",
        "kind": "rss",
        "tags": ["factor", "momentum", "value", "quality", "evidence_based"],
        "weight": 0.9,
    },
    {
        "name": "cfa_institute_rf",
        "label": "CFA Institute Research Foundation",
        "category": "blog",
        "url": "https://rpc.cfainstitute.org/en/research-foundation/publications/_jcr_content/root/responsivegrid/pagecontentgrid/pagecontents/contents/text/links/feed",
        "kind": "rss",
        "tags": ["investment", "asset_allocation", "risk", "factor", "academic"],
        "weight": 0.7,
    },
    {
        "name": "two_centuries_investments",
        "label": "Two Centuries Investments Blog",
        "category": "blog",
        "url": "https://www.twocenturies.com/blog?format=rss",
        "kind": "rss",
        "tags": ["value", "momentum", "factor", "historical", "long_term"],
        "weight": 0.7,
    },
    {
        "name": "philosophical_economics",
        "label": "Philosophical Economics",
        "category": "blog",
        "url": "https://www.philosophicaleconomics.com/feed/",
        "kind": "rss",
        "tags": ["valuation", "macro", "equity", "bonds", "asset_allocation"],
        "weight": 0.6,
    },
    {
        "name": "marketsci",
        "label": "MarketSci Blog",
        "category": "blog",
        "url": "https://marketsci.wordpress.com/feed/",
        "kind": "rss",
        "tags": ["system", "momentum", "mean_reversion", "backtest", "ETF"],
        "weight": 0.8,
    },
    {
        "name": "investment_idiocy",
        "label": "Investment Idiocy (Rob Carver)",
        "category": "blog",
        "url": "https://investment-idiocy.blogspot.com/feeds/posts/default",
        "kind": "rss",
        "tags": ["systematic", "futures", "trend_following", "risk", "sizing"],
        "weight": 0.9,
    },
    {
        "name": "systematic_investor",
        "label": "Systematic Investor Blog",
        "category": "blog",
        "url": "https://systematicinvestor.github.io/feed.xml",
        "kind": "rss",
        "tags": ["systematic", "R", "backtest", "portfolio", "risk"],
        "weight": 0.7,
    },
    {
        "name": "tr8dr",
        "label": "tr8dr (Quant Practitioner)",
        "category": "blog",
        "url": "https://tr8dr.wordpress.com/feed/",
        "kind": "rss",
        "tags": ["market_microstructure", "execution", "HFT", "signals", "python"],
        "weight": 0.8,
    },
    # ── CRYPTO NEWS & RESEARCH ────────────────────────────────────────────────
    {
        "name": "coindesk",
        "label": "CoinDesk News",
        "category": "crypto",
        "url": "https://www.coindesk.com/arc/outboundfeeds/rss/",
        "kind": "rss",
        "tags": ["crypto", "bitcoin", "ethereum", "regulation", "institutional"],
        "weight": 0.7,
    },
    {
        "name": "cointelegraph",
        "label": "Cointelegraph",
        "category": "crypto",
        "url": "https://cointelegraph.com/rss",
        "kind": "rss",
        "tags": ["crypto", "defi", "nft", "regulation", "bitcoin", "ethereum"],
        "weight": 0.6,
    },
    {
        "name": "decrypt_news",
        "label": "Decrypt",
        "category": "crypto",
        "url": "https://decrypt.co/feed",
        "kind": "rss",
        "tags": ["crypto", "web3", "bitcoin", "ethereum", "regulation"],
        "weight": 0.6,
    },
    {
        "name": "the_block",
        "label": "The Block Research",
        "category": "crypto",
        "url": "https://www.theblock.co/rss.xml",
        "kind": "rss",
        "tags": ["crypto", "institutional", "trading", "data", "volume"],
        "weight": 0.8,
    },
    {
        "name": "bankless",
        "label": "Bankless",
        "category": "crypto",
        "url": "https://www.bankless.com/rss",
        "kind": "rss",
        "tags": ["ethereum", "defi", "yield", "staking", "protocol"],
        "weight": 0.6,
    },
    {
        "name": "bitcoin_magazine",
        "label": "Bitcoin Magazine",
        "category": "crypto",
        "url": "https://bitcoinmagazine.com/.rss/full/",
        "kind": "rss",
        "tags": ["bitcoin", "macro", "monetary", "adoption"],
        "weight": 0.5,
    },
    {
        "name": "dlnews",
        "label": "DL News (DeFi/Crypto)",
        "category": "crypto",
        "url": "https://www.dlnews.com/feed/",
        "kind": "rss",
        "tags": ["defi", "crypto", "regulation", "institutional"],
        "weight": 0.6,
    },
    {
        "name": "coingecko_market",
        "label": "CoinGecko Market Data",
        "category": "crypto",
        "url": "coingecko_api",
        "kind": "coingecko_api",
        "tags": ["crypto", "price", "volume", "market_cap", "trending"],
        "weight": 0.8,
    },
    # ── INDUSTRY / MACRO ──────────────────────────────────────────────────────
    {
        "name": "fred_notes",
        "label": "FRED Economic Data Blog",
        "category": "industry",
        "url": "https://fredblog.stlouisfed.org/feed/",
        "kind": "rss",
        "tags": ["macro", "economics", "inflation", "rates", "employment"],
        "weight": 0.5,
    },
    {
        "name": "bis_qrb",
        "label": "BIS Quarterly Review",
        "category": "industry",
        "url": "https://www.bis.org/dcms/feeds/rss_cbspeech.xml",
        "kind": "rss",
        "tags": ["macro", "central_bank", "rates", "systemic", "regulatory"],
        "weight": 0.5,
    },
    {
        "name": "cme_education",
        "label": "CME Group Education",
        "category": "industry",
        "url": "https://www.cmegroup.com/insights/articles.rss",
        "kind": "rss",
        "tags": ["futures", "derivatives", "hedging", "volatility", "execution"],
        "weight": 0.7,
    },
    {
        "name": "risk_net",
        "label": "Risk.net (Quant Finance)",
        "category": "industry",
        "url": "https://www.risk.net/rss",
        "kind": "rss",
        "tags": ["risk", "derivatives", "regulation", "quant", "systematic"],
        "weight": 0.8,
    },
    {
        "name": "cboe_insights",
        "label": "CBOE Insights",
        "category": "industry",
        "url": "https://www.cboe.com/insights/feed/",
        "kind": "rss",
        "tags": ["volatility", "options", "VIX", "derivatives", "hedging"],
        "weight": 0.6,
    },
    # ── DATA SCIENCE / PYTHON ─────────────────────────────────────────────────
    {
        "name": "pydata_blog",
        "label": "PyData Blog",
        "category": "ml",
        "url": "https://pydata.org/feed.rss",
        "kind": "rss",
        "tags": ["python", "data_science", "pandas", "numpy", "time_series"],
        "weight": 0.5,
    },
    {
        "name": "real_python",
        "label": "Real Python",
        "category": "ml",
        "url": "https://realpython.com/atom.xml",
        "kind": "rss",
        "tags": ["python", "tutorial", "library", "finance", "data"],
        "weight": 0.4,
    },
    {
        "name": "reddit_datascience",
        "label": "Reddit r/datascience",
        "category": "ml",
        "url": "https://www.reddit.com/r/datascience/top/.rss?t=week",
        "kind": "rss",
        "tags": ["data_science", "machine_learning", "statistics", "python"],
        "weight": 0.4,
    },
    # ── NEWSLETTERS / AGGREGATORS ─────────────────────────────────────────────
    {
        "name": "import_ai",
        "label": "ImportAI Newsletter",
        "category": "ml",
        "url": "https://importai.substack.com/feed",
        "kind": "rss",
        "tags": ["AI", "LLM", "deep_learning", "research", "safety"],
        "weight": 0.5,
    },
    {
        "name": "agi_safety_newsletter",
        "label": "AI Alignment Forum",
        "category": "ml",
        "url": "https://www.alignmentforum.org/feed.xml",
        "kind": "rss",
        "tags": ["AI", "agent", "reasoning", "alignment"],
        "weight": 0.3,
    },
    {
        "name": "epsilon_theory",
        "label": "Epsilon Theory (Macro+Quant)",
        "category": "blog",
        "url": "https://www.epsilontheory.com/feed/",
        "kind": "rss",
        "tags": ["macro", "narrative", "behavior", "market_regime", "strategy"],
        "weight": 0.6,
    },
    {
        "name": "new_things_under_sun",
        "label": "New Things Under the Sun",
        "category": "blog",
        "url": "https://www.newthingsunderthesun.com/feed",
        "kind": "rss",
        "tags": ["economics", "innovation", "productivity", "macro"],
        "weight": 0.3,
    },
    {
        "name": "capital_spectator",
        "label": "Capital Spectator",
        "category": "blog",
        "url": "https://www.capitalspectator.com/feed/",
        "kind": "rss",
        "tags": ["macro", "asset_allocation", "ETF", "regime", "momentum"],
        "weight": 0.6,
    },
    {
        "name": "abnormal_returns",
        "label": "Abnormal Returns",
        "category": "blog",
        "url": "https://abnormalreturns.com/feed/",
        "kind": "rss",
        "tags": ["investment", "links", "research", "behavioral", "factor"],
        "weight": 0.7,
    },
    {
        "name": "financial_hacker",
        "label": "Financial Hacker (Zorro)",
        "category": "blog",
        "url": "https://financial-hacker.com/feed/",
        "kind": "rss",
        "tags": ["algo_trading", "backtest", "C", "system", "strategy"],
        "weight": 0.7,
    },
    {
        "name": "following_the_trend",
        "label": "Following the Trend (Andreas Clenow)",
        "category": "blog",
        "url": "https://www.followingthetrend.com/feed/",
        "kind": "rss",
        "tags": ["trend_following", "momentum", "CTA", "futures", "systematic"],
        "weight": 0.9,
    },
]

# Build quick lookup by name
SOURCE_BY_NAME: Dict[str, Dict[str, Any]] = {s["name"]: s for s in SOURCES}

# NEXUS topic keywords used for relevance scoring
NEXUS_KEYWORDS: List[str] = [
    # Core quant
    "momentum", "carry", "mean reversion", "trend following", "cross-sectional",
    "time series", "factor model", "alpha", "beta", "sharpe", "calmar",
    "drawdown", "volatility", "risk parity", "mean variance",
    # Crypto specific
    "crypto", "bitcoin", "ethereum", "defi", "funding rate", "perpetual",
    "binance", "basis", "arbitrage", "yield", "staking",
    # ML
    "machine learning", "deep learning", "reinforcement learning", "lstm",
    "transformer", "neural network", "xgboost", "random forest", "gradient boost",
    "feature engineering", "backtest", "overfitting", "walk-forward",
    # Risk
    "var", "cvar", "maximum drawdown", "position sizing", "kelly",
    "correlation", "regime", "covariance", "hedging",
    # Strategy types
    "long short", "market neutral", "dollar neutral", "leverage",
    "rebalancing", "execution", "slippage", "transaction cost",
    # Academic terms
    "out-of-sample", "statistical significance", "p-value",
    "portfolio optimization", "expected return", "asset pricing",
]


def get_sources_by_category(category: str) -> List[Dict[str, Any]]:
    return [s for s in SOURCES if s["category"] == category]


def get_sources_by_kind(kind: str) -> List[Dict[str, Any]]:
    return [s for s in SOURCES if s["kind"] == kind]
