#!/usr/bin/env R

# NEXUS dashboard generator (R template)
# Usage (after R is installed):
#   Rscript scripts/generate_nexus_live_dashboard.R

suppressWarnings({
  if (!requireNamespace("jsonlite", quietly = TRUE)) {
    stop("Please install jsonlite: install.packages('jsonlite')")
  }
})

escape_html <- function(x) {
  x <- gsub("&", "&amp;", x, fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  x <- gsub(">", "&gt;", x, fixed = TRUE)
  x
}

project_rows_html <- function(track) {
  keys <- c("crypto_perps", "crypto_options", "commodity_cta")
  rows <- character(0)
  for (k in keys) {
    p <- track$projects[[k]]
    pass <- ifelse(p$avg_sharpe >= p$target_sharpe, "PASS", "FAIL")
    klass <- ifelse(pass == "PASS", "pass", "fail")
    rows <- c(
      rows,
      paste0(
        "<tr>",
        "<td><code>", k, "</code></td>",
        "<td>", p$status, "</td>",
        "<td>", p$target_sharpe, "</td>",
        "<td>", p$avg_sharpe, "</td>",
        "<td>", p$min_sharpe, "</td>",
        "<td>", p$max_sharpe, "</td>",
        "<td><span class='pill ", klass, "'>", pass, "</span></td>",
        "</tr>"
      )
    )
  }
  paste(rows, collapse = "\n")
}

repo <- normalizePath(".", mustWork = TRUE)
out_html <- file.path(repo, "artifacts", "reports", "nexus_live_dashboard_from_r.html")

d <- jsonlite::fromJSON(file.path(repo, "artifacts", "track_record.json"), simplifyVector = TRUE)
cta <- jsonlite::fromJSON(file.path(repo, "artifacts", "commodity_cta_wf.json"), simplifyVector = TRUE)

keys <- c("crypto_perps", "crypto_options", "commodity_cta")
pass_count <- sum(vapply(keys, function(k) d$projects[[k]]$avg_sharpe >= d$projects[[k]]$target_sharpe, logical(1)))
pass_pct <- round(100 * pass_count / length(keys), 0)

git_head <- tryCatch(
  system("git rev-parse --short=12 origin/main", intern = TRUE),
  error = function(e) "N/A"
)

git_commits <- tryCatch(
  system("git log --oneline -n 12 origin/main", intern = TRUE),
  error = function(e) character(0)
)
commit_items <- if (length(git_commits) > 0) {
  paste(sprintf("<li><code>%s</code> %s</li>",
                sub(" .*", "", git_commits),
                escape_html(sub("^[^ ]+ ", "", git_commits))), collapse = "\n")
} else {
  "<li>No commit data</li>"
}

html <- paste0(
"<!doctype html>
<html lang='en'>
<head>
  <meta charset='utf-8' />
  <meta name='viewport' content='width=device-width, initial-scale=1' />
  <title>NEXUS Live Dashboard (R)</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 24px; background: #f7f7f7; color: #1f2529; }
    .card { background: #fff; border: 1px solid #ddd; border-radius: 10px; padding: 14px; margin-bottom: 14px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th, td { padding: 8px; border-bottom: 1px solid #eee; text-align: left; }
    .pill { color: #fff; border-radius: 999px; padding: 2px 8px; font-size: 11px; }
    .pass { background: #1f8f55; }
    .fail { background: #cb3b31; }
    code { background: #eef3ff; padding: 1px 5px; border-radius: 5px; }
  </style>
</head>
<body>
  <div class='card'>
    <h2>NEXUS Dashboard (Generated by R)</h2>
    <p>Generated: ", Sys.time(), "</p>
    <p>Metrics snapshot: ", d$last_updated, "</p>
    <p>origin/main: <code>", git_head[1], "</code></p>
    <p>Benchmark pass count: ", pass_count, "/3 (", pass_pct, "%)</p>
  </div>

  <div class='card'>
    <h3>Project Benchmark Table</h3>
    <table>
      <thead>
        <tr><th>Project</th><th>Status</th><th>Target</th><th>Avg</th><th>Min</th><th>Max</th><th>Pass</th></tr>
      </thead>
      <tbody>
", project_rows_html(d), "
      </tbody>
    </table>
  </div>

  <div class='card'>
    <h3>Commodity CTA WF</h3>
    <p>Verdict: ", cta$verdict, " | OOS min: ", cta$oos_min, " | OOS avg: ", cta$oos_avg, " | Full Sharpe: ", cta$periods$FULL$sharpe, "</p>
  </div>

  <div class='card'>
    <h3>Latest Commits</h3>
    <ul>
", commit_items, "
    </ul>
  </div>
</body>
</html>"
)

dir.create(dirname(out_html), recursive = TRUE, showWarnings = FALSE)
writeLines(html, out_html, useBytes = TRUE)
cat(out_html, "\n")
